name: Release Tag & Deploy

on:
  push:
    branches:
      - master

jobs:
  tag-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        id: branch
        run: |
          echo "branch_ref=$(git log -1 --pretty=format:'%D' | grep -o 'origin/release/[^, ]*' | head -n1 | sed 's/origin\///')" >> $GITHUB_OUTPUT

      - name: Set tag version
        id: tag
        run: |
          branch="${{ steps.branch.outputs.branch_ref }}"
          if [[ "$branch" =~ release/v([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
            tag="${BASH_REMATCH[1]}"
            tag="v$tag"
          else
            last_tag=$(git describe --tags --abbrev=0 || echo "v0.0.0")
            IFS='.' read -r v1 v2 v3 <<< "${last_tag#v}"
            tag="v$((v1)).$((v2)).$((v3+1))"
          fi
          echo "TAG=$tag" >> $GITHUB_ENV

      - name: Create and push tag (PAT)
        env:
          PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag $TAG
          git push https://x-access-token:${PAT}@github.com/${{ github.repository }} $TAG

      - name: Wait for Tag push
        run: sleep 5
